// Generates supabase/seed.sql from js/data.js so the live catalog matches MOCK
// byte-for-byte (same ids, prices, ratings, flags, images). Run:
//     node supabase/gen_seed.mjs
// Writes supabase/seed.sql (paste into the Supabase SQL editor, or use db push).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// --- load js/data.js (it only touches `window`) -----------------------------
const code = readFileSync(join(root, "js", "data.js"), "utf8");
const win = {};
new Function("window", `${code}\n;return window;`)(win);
const PRODUCTS = win.MOCK_PRODUCTS;
const CATS = win.CATS;
if (!PRODUCTS?.length || !CATS) throw new Error("could not read MOCK_PRODUCTS/CATS");

// --- helpers ----------------------------------------------------------------
const q = (s) => `'${String(s ?? "").replace(/'/g, "''")}'`;
const slugify = (s) =>
  s.toLowerCase().replace(/["']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const parseRating = (r) => {
  const m = /^([\d.]+)\s*\(?\s*([\d.]+)(k?)\s*\)?/.exec(String(r || ""));
  if (!m) return { rating: "null", count: 0 };
  const count = Math.round(parseFloat(m[2]) * (m[3] === "k" ? 1000 : 1));
  return { rating: m[1], count };
};

// --- categories (skip the synthetic "All") ----------------------------------
const catRows = Object.entries(CATS)
  .filter(([slug]) => slug !== "All")
  .map(([slug, c], i) => [slug, c.t, c.d || "", c.img || "", i + 1]);

// --- brands -----------------------------------------------------------------
const brands = [...new Set(PRODUCTS.map((p) => p.b))].sort();

// --- emit -------------------------------------------------------------------
const L = [];
L.push("-- ============================================================================");
L.push("-- VoltEdge seed catalog - GENERATED by supabase/gen_seed.mjs from js/data.js.");
L.push("-- Do NOT hand-edit; re-run `node supabase/gen_seed.mjs` to regenerate.");
L.push("-- Run AFTER migrations. Safe to re-run (catalog conflicts are ignored).");
L.push("-- ============================================================================");
L.push("");
L.push("-- Checkout validates this coupon server-side in create_order().");
L.push("insert into public.coupons(code,percent_off,min_subtotal,active) values");
L.push("  ('VOLT10',10,0,true)");
L.push("on conflict (code) do update set percent_off=excluded.percent_off,");
L.push("  min_subtotal=excluded.min_subtotal,active=excluded.active;");
L.push("");
L.push("insert into public.categories(slug,title,description,image_url,sort_order) values");
L.push(
  catRows
    .map(([slug, t, d, img, o]) => `  (${q(slug)},${q(t)},${q(d)},${q(img)},${o})`)
    .join(",\n")
);
L.push("on conflict (slug) do nothing;");
L.push("");
L.push("insert into public.brands(name) values");
L.push(brands.map((b) => `  (${q(b)})`).join(",\n"));
L.push("on conflict (name) do nothing;");
L.push("");
L.push(
  "insert into public.products(id,slug,name,category_id,brand_id,price,compare_at,rating,rating_count,flag,image_url,stock,is_active) values"
);
L.push(
  PRODUCTS.map((p) => {
    const { rating, count } = parseRating(p.r);
    return (
      `  (${p.id},${q(slugify(p.n))},${q(p.n)},` +
      `(select id from public.categories where slug=${q(p.c)}),` +
      `(select id from public.brands where name=${q(p.b)}),` +
      `${p.p},${p.o ?? "null"},${rating},${count},` +
      `${q(p.f)},${q(p.img)},25,true)`
    );
  }).join(",\n")
);
L.push("on conflict (id) do nothing;");
L.push("");
L.push("-- keep identity sequences ahead of the seeded ids");
L.push("select setval(pg_get_serial_sequence('public.products','id'), greatest((select max(id) from public.products),1));");
L.push("select setval(pg_get_serial_sequence('public.categories','id'), greatest((select max(id) from public.categories),1));");
L.push("select setval(pg_get_serial_sequence('public.brands','id'), greatest((select max(id) from public.brands),1));");
L.push("");

writeFileSync(join(here, "seed.sql"), L.join("\n"), "utf8");
console.log(`wrote supabase/seed.sql — ${catRows.length} categories, ${brands.length} brands, ${PRODUCTS.length} products`);
