-- ============================================================================
-- VoltEdge seed catalog - GENERATED by supabase/gen_seed.mjs from js/data.js.
-- Do NOT hand-edit; re-run `node supabase/gen_seed.mjs` to regenerate.
-- Run AFTER migrations. Safe to re-run (catalog conflicts are ignored).
-- ============================================================================

-- Checkout validates this coupon server-side in create_order().
insert into public.coupons(code,percent_off,min_subtotal,active) values
  ('VOLT10',10,0,true)
on conflict (code) do update set percent_off=excluded.percent_off,
  min_subtotal=excluded.min_subtotal,active=excluded.active;

insert into public.categories(slug,title,description,image_url,sort_order) values
  ('Laptops','Laptops','Ultrabooks and gaming laptops.','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=70&auto=format&fit=crop',1),
  ('Phones','Smartphones','Flagships with pro cameras.','https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=70&auto=format&fit=crop',2),
  ('Audio','Audio','ANC earbuds and headphones.','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=70&auto=format&fit=crop',3),
  ('Wearables','Wearables','Watches with 21-day battery.','https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=70&auto=format&fit=crop',4),
  ('Gaming','Gaming','RTX rigs and 240Hz gear.','https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=70&auto=format&fit=crop',5),
  ('TVs','TVs & Home Entertainment','QLED 4K TVs and soundbars.','https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=70&auto=format&fit=crop',6),
  ('Cameras','Cameras','Mirrorless, action, drones.','https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=70&auto=format&fit=crop',7),
  ('Accessories','Accessories','Chargers, hubs and docks.','https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=70&auto=format&fit=crop',8),
  ('Smart Home','Smart Home','Security and lighting.','https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&q=70&auto=format&fit=crop',9),
  ('Networking','Networking','WiFi 6, mesh, switches.','https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&q=70&auto=format&fit=crop',10)
on conflict (slug) do nothing;

insert into public.brands(name) values
  ('ActionCam'),
  ('Aura'),
  ('CinemaBar'),
  ('Echo'),
  ('Falcon'),
  ('Glow'),
  ('Luma'),
  ('MeshForce'),
  ('NovaTech'),
  ('Photon'),
  ('ProShot'),
  ('Pulse'),
  ('SecureCam'),
  ('Sentinel'),
  ('SonicMax'),
  ('SwitchPro'),
  ('Titan'),
  ('VisionMax'),
  ('VoltEdge'),
  ('Vortex')
on conflict (name) do nothing;

insert into public.products(id,slug,name,category_id,brand_id,price,compare_at,rating,rating_count,flag,image_url,stock,is_active) values
  (1,'novabook-pro-14-oled','NovaBook Pro 14 OLED',(select id from public.categories where slug='Laptops'),(select id from public.brands where name='NovaTech'),1899,2499,4.9,2100,'-24%','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&q=70&auto=format&fit=crop',25,true),
  (2,'photon-15-ultra-phone','Photon 15 Ultra Phone',(select id from public.categories where slug='Phones'),(select id from public.brands where name='Photon'),999,1199,4.8,5400,'-17%','https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&q=70&auto=format&fit=crop',25,true),
  (3,'aura-buds-pro-anc','Aura Buds Pro ANC',(select id from public.categories where slug='Audio'),(select id from public.brands where name='Aura'),129,199,4.9,12000,'HOT','https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=70&auto=format&fit=crop',25,true),
  (4,'pulse-fit-s-watch','Pulse Fit S Watch',(select id from public.categories where slug='Wearables'),(select id from public.brands where name='Pulse'),249,329,4.7,3200,'NEW','https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=70&auto=format&fit=crop',25,true),
  (5,'vortex-rtx-gaming-rig','Vortex RTX Gaming Rig',(select id from public.categories where slug='Gaming'),(select id from public.brands where name='Vortex'),2199,2599,4.9,890,'-15%','https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500&q=70&auto=format&fit=crop',25,true),
  (6,'echo-dome-speaker','Echo Dome Speaker',(select id from public.categories where slug='Smart Home'),(select id from public.brands where name='Echo'),89,129,4.6,8000,'-31%','https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&q=70&auto=format&fit=crop',25,true),
  (7,'sonicmax-headphones','SonicMax Headphones',(select id from public.categories where slug='Audio'),(select id from public.brands where name='SonicMax'),349,449,4.8,6000,'-22%','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=70&auto=format&fit=crop',25,true),
  (8,'voltcharge-140w-gan','VoltCharge 140W GaN',(select id from public.categories where slug='Accessories'),(select id from public.brands where name='VoltEdge'),69,99,4.7,4000,'NEW','https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&q=70&auto=format&fit=crop',25,true),
  (9,'visionmax-55-qled-4k-tv','VisionMax 55 QLED 4K TV',(select id from public.categories where slug='TVs'),(select id from public.brands where name='VisionMax'),749,899,4.8,3400,'HOT','https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&q=70&auto=format&fit=crop',25,true),
  (10,'visionmax-65-qled-soundbar-bundle','VisionMax 65 QLED + Soundbar Bundle',(select id from public.categories where slug='TVs'),(select id from public.brands where name='VisionMax'),1199,1499,4.9,1200,'-20%','https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&q=70&auto=format&fit=crop',25,true),
  (11,'cinemabar-5-1-dolby-soundbar','CinemaBar 5.1 Dolby Soundbar',(select id from public.categories where slug='TVs'),(select id from public.brands where name='CinemaBar'),299,399,4.7,5100,'-25%','https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&q=70&auto=format&fit=crop',25,true),
  (12,'luma-m50-mirrorless-camera','Luma M50 Mirrorless Camera',(select id from public.categories where slug='Cameras'),(select id from public.brands where name='Luma'),899,1099,4.9,980,'-18%','https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&q=70&auto=format&fit=crop',25,true),
  (13,'actioncam-4k-waterproof','ActionCam 4K Waterproof',(select id from public.categories where slug='Cameras'),(select id from public.brands where name='ActionCam'),249,329,4.7,6300,'NEW','https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500&q=70&auto=format&fit=crop',25,true),
  (14,'proshot-4k-drone','ProShot 4K Drone',(select id from public.categories where slug='Cameras'),(select id from public.brands where name='ProShot'),699,899,4.8,2200,'HOT','https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=500&q=70&auto=format&fit=crop',25,true),
  (15,'luma-50mm-f-1-8-lens','Luma 50mm f/1.8 Lens',(select id from public.categories where slug='Cameras'),(select id from public.brands where name='Luma'),199,259,4.9,1500,'-23%','https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500&q=70&auto=format&fit=crop',25,true),
  (16,'magdock-3-in-1-wireless-charger','MagDock 3-in-1 Wireless Charger',(select id from public.categories where slug='Accessories'),(select id from public.brands where name='VoltEdge'),79,99,4.6,9000,'-20%','https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?w=500&q=70&auto=format&fit=crop',25,true),
  (17,'titan-usb-c-11-in-1-hub','Titan USB-C 11-in-1 Hub',(select id from public.categories where slug='Accessories'),(select id from public.brands where name='Titan'),129,159,4.8,4100,'NEW','https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&q=70&auto=format&fit=crop',25,true),
  (18,'securecam-360-indoor','SecureCam 360 Indoor',(select id from public.categories where slug='Smart Home'),(select id from public.brands where name='SecureCam'),79,109,4.6,7000,'-28%','https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=500&q=70&auto=format&fit=crop',25,true),
  (19,'sentinel-video-doorbell','Sentinel Video Doorbell',(select id from public.categories where slug='Smart Home'),(select id from public.brands where name='Sentinel'),149,199,4.7,3800,'NEW','https://images.unsplash.com/photo-1558002038-1055907df827?w=500&q=70&auto=format&fit=crop',25,true),
  (20,'glowstrip-led-starter-kit','GlowStrip LED Starter Kit',(select id from public.categories where slug='Smart Home'),(select id from public.brands where name='Glow'),39,59,4.5,11000,'-34%','https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500&q=70&auto=format&fit=crop',25,true),
  (21,'falcon-ax6000-wifi-6-router','Falcon AX6000 WiFi 6 Router',(select id from public.categories where slug='Networking'),(select id from public.brands where name='Falcon'),199,269,4.8,5500,'HOT','https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=500&q=70&auto=format&fit=crop',25,true),
  (22,'meshforce-whole-home-wifi-3-pack','MeshForce Whole-Home WiFi 3-Pack',(select id from public.categories where slug='Networking'),(select id from public.brands where name='MeshForce'),349,449,4.9,2800,'NEW','https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&q=70&auto=format&fit=crop',25,true),
  (23,'switchpro-8-port-2-5g-switch','SwitchPro 8-Port 2.5G Switch',(select id from public.categories where slug='Networking'),(select id from public.brands where name='SwitchPro'),89,119,4.7,1900,'-25%','https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&q=70&auto=format&fit=crop',25,true),
  (24,'aerobook-air-13-m3','AeroBook Air 13 M3',(select id from public.categories where slug='Laptops'),(select id from public.brands where name='NovaTech'),1099,1299,4.8,1800,'-15%','https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&q=70&auto=format&fit=crop',25,true)
on conflict (id) do nothing;

-- keep identity sequences ahead of the seeded ids
select setval(pg_get_serial_sequence('public.products','id'), greatest((select max(id) from public.products),1));
select setval(pg_get_serial_sequence('public.categories','id'), greatest((select max(id) from public.categories),1));
select setval(pg_get_serial_sequence('public.brands','id'), greatest((select max(id) from public.brands),1));
