#!/usr/bin/env node
// scripts/build-env.mjs
// Reads the Supabase URL + publishable key from the environment (process.env or
// the git-ignored .env file) and writes js/env.js — the only artifact the
// browser loads to get window.__ENV__. Regenerate after changing .env.
//
//   node scripts/build-env.mjs
//
// .env and js/env.js are both git-ignored, so no key is ever committed.
// A service_role / sb_secret_ key is rejected outright.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT, loadEnv, supabaseConfig, looksPrivileged } from "./load-env.mjs";

const get = loadEnv();
const { url, key, useFlag } = supabaseConfig(get);

if (looksPrivileged(key)){
  console.error("[build-env] REFUSING to build: that key looks like a service_role / secret key.");
  console.error("[build-env] Only the publishable (anon) key may be shipped to the browser.");
  process.exit(1);
}
if (url && !/^https?:\/\//.test(url)){
  console.error(`[build-env] SUPABASE_URL must be a full URL (https://...). Got: "${url}"`);
  process.exit(1);
}

const configured = !!(url && key);
const useSupabase = useFlag ? useFlag !== "false" : configured;

const payload = { SUPABASE_URL: url, SUPABASE_PUBLISHABLE_KEY: key, USE_SUPABASE: useSupabase };
const banner =
  "// AUTO-GENERATED by scripts/build-env.mjs - DO NOT EDIT, DO NOT COMMIT.\n" +
  "// Values come from .env / process.env. Regenerate with: node scripts/build-env.mjs\n";
writeFileSync(join(ROOT, "js", "env.js"), `${banner}window.__ENV__=${JSON.stringify(payload)};\n`, "utf8");

console.log("[build-env] wrote js/env.js");
console.log(`[build-env] SUPABASE_URL = ${url || "(empty)"}`);
console.log(`[build-env] key          = ${key ? key.slice(0, 12) + "... (" + key.length + " chars)" : "(empty)"}`);
console.log(`[build-env] mode         = ${configured && useSupabase ? "LIVE (Supabase)" : "MOCK"}`);
if (!configured) console.log("[build-env] tip: copy .env.example to .env and fill in your project URL + publishable key.");