-- ============================================================================
-- VoltEdge — Supabase schema v1  (supabase/migrations/0001_init.sql)
-- ----------------------------------------------------------------------------
-- STATUS: APPLIED — this schema is live on project vcidcyfuwfbndidjpajn.
-- Verified 2026-10-01: 11 tables created, RLS enabled, create_order() present,
-- and the 24-product catalog loaded from supabase/seed.sql. This file remains the
-- source of truth for the backend; re-running it is idempotent (create ... if not
-- exists / create or replace / drop policy if exists).
--
-- Money conventions (kept identical to the frontend so nothing double-converts):
--   * products.price / compare_at  = USD catalog values (js/data.js MOCK uses USD;
--     the UI renders them as NGN via APP_CONFIG.RATE * DISCOUNT).
--   * orders.subtotal/discount/shipping/total = display currency (NGN), matching
--     js/checkout.js totals().
--
-- Apply with:  supabase db push        (or paste into the SQL editor)
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------- helpers ----------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

-- ---------- catalog ----------
create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  title       text not null,
  description text default '',
  image_url   text default '',
  sort_order  int default 0,
  created_at  timestamptz not null default now()
);

create table if not exists public.brands (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id           bigint generated by default as identity primary key,
  slug         text not null unique,
  name         text not null,
  category_id  bigint references public.categories(id) on delete set null,
  brand_id     bigint references public.brands(id) on delete set null,
  price        numeric(12,2) not null check (price >= 0),   -- USD catalog price
  compare_at   numeric(12,2),                               -- "was" price (USD)
  rating       numeric(2,1) check (rating between 0 and 5),
  rating_count int not null default 0,
  flag         text default '',            -- Deal / New / Best Seller ...
  image_url    text default '',
  description  text default '',
  stock        int not null default 0,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_brand_idx    on public.products(brand_id);
create index if not exists products_active_idx   on public.products(is_active);

drop trigger if exists trg_products_updated on public.products;
create trigger trg_products_updated before update on public.products
  for each row execute function public.set_updated_at();

-- ---------- accounts ----------
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  full_name  text default '',
  phone      text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- auto-create a profile row on signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, full_name, phone)
  values (new.id,
          coalesce(new.raw_user_meta_data->>'full_name',''),
          coalesce(new.raw_user_meta_data->>'phone',''))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create table if not exists public.addresses (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  label      text default '',
  recipient  text not null,
  phone      text default '',
  line1      text not null,
  city       text not null,
  state      text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists addresses_user_idx on public.addresses(user_id);

create table if not exists public.wishlists (
  user_id    uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ---------- commerce ----------
create table if not exists public.coupons (
  code         text primary key,
  percent_off  int not null check (percent_off between 1 and 100),
  min_subtotal numeric(12,2) not null default 0,
  active       boolean not null default true,
  expires_at   timestamptz,
  created_at   timestamptz not null default now()
);

create table if not exists public.orders (
  id           uuid primary key default gen_random_uuid(),
  order_no     text not null unique,
  user_id      uuid references auth.users(id) on delete set null,
  email        text,
  contact_name text,
  phone        text,
  address      text,
  city         text,
  state        text,
  note         text,
  ship_opt     text,
  ship_label   text,
  eta          text,
  pay_method   text,
  coupon       text,
  subtotal     numeric(12,2) not null default 0,   -- NGN (display currency)
  discount     numeric(12,2) not null default 0,
  shipping     numeric(12,2) not null default 0,
  total        numeric(12,2) not null default 0,
  status       text not null default 'Processing',
  created_at   timestamptz not null default now()
);
create index if not exists orders_user_idx    on public.orders(user_id);
create index if not exists orders_created_idx on public.orders(created_at desc);

create table if not exists public.order_items (
  id         bigint generated by default as identity primary key,
  order_id   uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  name       text not null,
  unit_price numeric(12,2) not null,   -- USD catalog price at time of order
  qty        int not null check (qty > 0),
  line_total numeric(12,2) not null
);
create index if not exists order_items_order_idx on public.order_items(order_id);

create table if not exists public.reviews (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  rating     int not null check (rating between 1 and 5),
  body       text default '',
  created_at timestamptz not null default now(),
  unique (product_id, user_id)
);

create table if not exists public.newsletter_subscribers (
  email      text primary key,
  created_at timestamptz not null default now()
);

-- ---------- order creation (server-authoritative totals) ----------
-- payload: {name,email,phone,address,city,state,note,shipOpt,shipLabel,eta,pay,
--           coupon,ship,items:[{id,qty}]}
-- Totals are recomputed from catalog prices + coupons; the client only supplies
-- product ids/qty + the shipping method (validated). Returns an app-shaped order
-- so the confirm screen (js/checkout.js) renders unchanged.
create or replace function public.create_order(payload jsonb)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  c_rate   constant numeric := 1400;   -- mirrors js/config.js RATE
  c_disc   constant numeric := 0.9;    -- mirrors js/config.js DISCOUNT
  v_items  jsonb := coalesce(payload->'items','[]'::jsonb);
  v_coupon text  := nullif(upper(trim(coalesce(payload->>'coupon',''))),'');
  v_pct    int   := 0;
  v_usd    numeric(12,2);
  v_sub    numeric(12,2);
  v_disc   numeric(12,2) := 0;
  v_ship   numeric(12,2);
  v_total  numeric(12,2);
  v_no     text;
  v_id     uuid;
  v_lines  jsonb := '[]'::jsonb;
  rec      record;
begin
  if jsonb_array_length(v_items) = 0 then raise exception 'create_order: empty cart'; end if;

  -- subtotal straight from the catalog (never trust client-sent prices)
  select coalesce(sum(p.price * (it->>'qty')::int),0) into v_usd
    from jsonb_array_elements(v_items) it
    join public.products p on p.id = (it->>'id')::bigint;
  if v_usd <= 0 then raise exception 'create_order: no valid items'; end if;
  v_sub := round(v_usd * c_rate * c_disc, 2);

  -- coupon
  if v_coupon is not null then
    select percent_off into v_pct from public.coupons
     where code = v_coupon and active
       and (expires_at is null or expires_at > now())
       and v_sub >= min_subtotal;
    v_pct := coalesce(v_pct,0);
  end if;
  if v_pct > 0 then v_disc := round(v_sub * v_pct / 100.0, 2); end if;

  -- shipping (validated against the allowed methods)
  v_ship := case coalesce(payload->>'shipOpt','0')
              when '4410' then 4410 when '10080' then 10080 else 0 end;
  v_total := v_sub - v_disc + v_ship;

  loop
    v_no := 'VE-' || lpad((floor(random()*1000000))::int::text, 6, '0');
    exit when not exists (select 1 from public.orders where order_no = v_no);
  end loop;

  insert into public.orders(order_no,user_id,email,contact_name,phone,address,city,state,
                            note,ship_opt,ship_label,eta,pay_method,coupon,
                            subtotal,discount,shipping,total)
  values (v_no, auth.uid(), payload->>'email', payload->>'name', payload->>'phone',
          payload->>'address', payload->>'city', payload->>'state', payload->>'note',
          payload->>'shipOpt', payload->>'shipLabel', payload->>'eta', payload->>'pay',
          v_coupon, v_sub, v_disc, v_ship, v_total)
  returning id into v_id;

  for rec in
    select p.id, p.name, p.price, p.image_url, (it->>'qty')::int as qty
      from jsonb_array_elements(v_items) it
      join public.products p on p.id = (it->>'id')::bigint
  loop
    insert into public.order_items(order_id,product_id,name,unit_price,qty,line_total)
    values (v_id, rec.id, rec.name, rec.price, rec.qty, rec.price*rec.qty);
    v_lines := v_lines || jsonb_build_object('id',rec.id,'n',rec.name,'img',rec.image_url,'p',rec.price,'qty',rec.qty);
  end loop;

  return json_build_object(
    'id', v_no, 'date', now(), 'status','Processing', 'items', v_lines,
    'sub', v_sub, 'disc', v_disc, 'ship', v_ship, 'total', v_total,
    'name', payload->>'name', 'email', payload->>'email', 'phone', payload->>'phone',
    'address', payload->>'address', 'city', payload->>'city', 'state', payload->>'state',
    'note', payload->>'note', 'shipOpt', payload->>'shipOpt', 'shipLabel', payload->>'shipLabel',
    'eta', payload->>'eta', 'pay', payload->>'pay', 'payMock', true, 'coupon', v_coupon
  );
end $$;

-- ---------- row level security ----------
alter table public.categories             enable row level security;
alter table public.brands                 enable row level security;
alter table public.products               enable row level security;
alter table public.profiles               enable row level security;
alter table public.addresses              enable row level security;
alter table public.wishlists              enable row level security;
alter table public.coupons                enable row level security;
alter table public.orders                 enable row level security;
alter table public.order_items            enable row level security;
alter table public.reviews                enable row level security;
alter table public.newsletter_subscribers enable row level security;

-- catalog: world-readable (writes only via service_role / dashboard)
drop policy if exists catalog_read_categories on public.categories;
create policy catalog_read_categories on public.categories for select using (true);
drop policy if exists catalog_read_brands on public.brands;
create policy catalog_read_brands on public.brands for select using (true);
drop policy if exists catalog_read_products on public.products;
create policy catalog_read_products on public.products for select using (is_active);

-- profiles / addresses / wishlists: owner only
drop policy if exists own_profile on public.profiles;
create policy own_profile on public.profiles for all
  using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists own_addresses on public.addresses;
create policy own_addresses on public.addresses for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_wishlist on public.wishlists;
create policy own_wishlist on public.wishlists for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- coupons: read-only for clients (re-validated inside create_order)
drop policy if exists read_coupons on public.coupons;
create policy read_coupons on public.coupons for select using (active);

-- orders: owner can read; writes happen only through create_order()
drop policy if exists own_orders_read on public.orders;
create policy own_orders_read on public.orders for select using (auth.uid() = user_id);
drop policy if exists own_order_items_read on public.order_items;
create policy own_order_items_read on public.order_items for select
  using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

-- reviews: public read, owner write
drop policy if exists read_reviews on public.reviews;
create policy read_reviews on public.reviews for select using (true);
drop policy if exists write_reviews_ins on public.reviews;
create policy write_reviews_ins on public.reviews for insert with check (auth.uid() = user_id);
drop policy if exists write_reviews_upd on public.reviews;
create policy write_reviews_upd on public.reviews for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists write_reviews_del on public.reviews;
create policy write_reviews_del on public.reviews for delete using (auth.uid() = user_id);

-- newsletter: anyone may subscribe; no public read
drop policy if exists newsletter_join on public.newsletter_subscribers;
create policy newsletter_join on public.newsletter_subscribers for insert with check (true);

-- ---------- grants ----------
grant usage on schema public to anon, authenticated;
grant select on public.categories, public.brands, public.products, public.coupons to anon, authenticated;
grant select on public.reviews to anon, authenticated;
grant insert, update, delete on public.reviews to authenticated;
grant select, insert, update, delete on public.profiles, public.addresses, public.wishlists to authenticated;
grant select on public.orders, public.order_items to authenticated;
grant insert on public.newsletter_subscribers to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on function public.create_order(jsonb) to anon, authenticated;

-- ---------- seed (safe to delete if you load your own catalog) ----------
insert into public.coupons(code,percent_off,min_subtotal,active) values
  ('VOLT10',10,0,true)
on conflict (code) do nothing;



